# Backend services needed for development.
#
# This file will start all the backend services needed to run InvenioRDM
# locally in development mode.
#
# Usage::
#
#   $ docker-compose up -d
#
# Following services are included:
# - Cache: Redis (exposed port: 6379)
# - DB: (PostgresSQL/MySQL) (exposed port: 5432 or 3306)
# - Message queue: RabbitMQ (exposed ports: 5672, 15672)
# - OpenSearch (exposed ports: 9200, 9600)
# - Kibana (view ES indexes) (exposed ports: 5601)
#
services:
  cache:
    extends:
      file: docker-services.yml
      service: cache
    networks:
      - am-d-model-repo-network
  db:
    extends:
      file: docker-services.yml
      service: db
    networks:
      - am-d-model-repo-network
  mq:
    extends:
      file: docker-services.yml
      service: mq
    networks:
      - am-d-model-repo-network
  search:
    extends:
      file: docker-services.yml
      service: search
    networks:
      - am-d-model-repo-network
  s3:
    extends:
      file: docker-services.yml
      service: s3
    networks:
      - am-d-model-repo-network
networks:
    am-d-model-repo-network:
        name: am-d-model-repo-network
volumes:
    data:
    redis_data:
